[package]
name = "freqfs"
version = "0.1.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
license = "Apache-2.0"
description = "An in-memory filesystem cache layer over tokio::fs, with LFU eviction"
repository = "https://github.com/haydnv/freqache"
readme = "README.md"

categories = ["caching", "filesystem", "memory-management"]
keywords = ["file", "io", "cache"]

[dependencies]
freqache = "0.4"
futures = "0.3"
tokio = { version = "1.11", features = ["fs", "io-util", "rt", "sync"] }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.11", features = ["macros"] }
